### ISSUE TITLE
feature request: copy path for wsl

### ISSUE THREAD

**Issue by char-iot** [baincd/vscode-copy-path-unixstyle#2]
Thanks for the extension. It's super useful!!!

basically the same as Copy Path (Unix Style).

Name: Copy Path for WSL
starts with /mnt/c/... or /mnt/d/... 
drive letter must be forced small letter, the rest is same as Unix Style.

still don't understand how could WSL devs forget this feature, Don't they all use MacBook Pro or WSL to develop!?

**Comment by baincd** [comment]
@char-iot Thank you for the kind words, and for the good suggestion!  I'm thinking about how to implement this (along with #1), while not adding a bunch of menu items that would just be clutter.  I have an idea how I might approach this, and will look into it when I find some time.

**Comment by baincd** [comment]
@char-iot I have added support for copying the path in WSL format.  You can change the format of the default command to WSL, or you can enable an additional command specifically to copy in WSL format.  

I would like to gather some feedback before releasing this to the VS Code Marketplace.  If you'd like to test and provide feedback, I would greatly appreciate it.  You can install pre-release [version 2.0.0-RC1](https://github.com/baincd/vscode-copy-path-unixstyle/releases/tag/v2.0.0-RC1) by downloading the .vsix file from the release page and installing in VS Code via the "Extensions: Install from VSIX" command.

**Comment by baincd** [comment]
@char-iot FYI, there is a newer pre-release version - [v2.0.0-RC2](https://github.com/baincd/vscode-copy-path-unixstyle/releases/tag/v2.0.0-RC2).

**Comment by char-iot** [comment]
@baincd Thanks a lot! Tried RC2. One issue, to use WSL path in VS Code Terminal directly, e.g. cd /mnt/c/repo, disk letter c, d, e etc. must be small letter.

**Comment by baincd** [comment]
@char-iot Thank you for the feedback.  Weirdly on my system the drive letter was lower case.  Oh, the joys of Windows :roll_eyes: 

I've created [v2.0.0-RC3](https://github.com/baincd/vscode-copy-path-unixstyle/releases/tag/v2.0.0-RC3), which forces the drive letter to lower case in WSL format (as well as Git Bash and Cygwin formats for good measure)

**Comment by char-iot** [comment]
@baincd  works! perfect!

**Comment by baincd** [comment]
Released as part of [v2.0.0](https://github.com/baincd/vscode-copy-path-unixstyle/releases/tag/v2.0.0).  Thank you for the feedback and testing!
